#!/sbin/nft -f


###
### Description: basic firewall for server
###
### Deny list:
###  - all traffic except rules in allow list
###  - icmp traffic
###  - reset packets
###  - ip rate over 100pkts/s
###
### Allow list:
###  - sshd port
###  - web server port
###  - output traffic
###

### variables
define int_sshd_port = 7345
define int_webserver_ports = { 80, 443 }

add table basic_firewall

## INPUT chain
add chain basic_firewall input { 
    # By default, drop all traffic unless it meets a filter
    # criteria specified by the rules that follow below.
    type filter hook input priority filter; policy drop;
}

## VAR: change pkt per second 
## 400 packets/second
add rule basic_firewall input limit rate over 400/second drop;
## VAR: change pkt size per second 
## 1Gbps
add rule basic_firewall input limit rate over 1048576 kbytes/second drop;

# Allow traffic from established and related packets, drop invalid
add rule basic_firewall input ct state vmap { established : accept, related : accept, invalid : drop };

# Allow loopback traffic.
add rule basic_firewall input iifname lo accept;

# allow rules
add rule basic_firewall input tcp dport $int_sshd_port accept;
add rule basic_firewall input tcp dport $int_webserver_ports accept;

