filetype off
set nocompatible

" rpt setup
set rtp+=~/.vim/bundle/Vundle.vim

" vundle setup
call vundle#begin()
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'altercation/vim-colors-solarized'
"Plugin 'dracula/vim'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'vim-airline/vim-airline'

Plugin 'fatih/vim-go', { 'for': 'go'}

Plugin 'pangloss/vim-javascript', { 'for': 'javascript'}
Plugin 'mattn/emmet-vim', { 'for': ['javascript', 'markdown', 'javascript.jsx', 'html']}
Plugin 'mxw/vim-jsx', { 'for': ['javascript', 'javascript.jsx']}

Plugin 'rust-lang/rust.vim', { 'for': 'rust'}

Plugin 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer --go-completer --js-completer --rust-completer', 'for': ['javascript', 'go', 'javascript.jsx', 'rust', 'c', 'cpp', 'rust']}
Plugin 'rdnetto/YCM-Generator', { 'branch': 'stable'}

Plugin 'shime/vim-livedown', { 'for': 'markdown', 'do': 'npm install'}

Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
Plugin 'junegunn/fzf.vim'

Plugin 'editorconfig/editorconfig-vim'
Plugin 'jiangmiao/auto-pairs'
call vundle#end()

" basic conf
set number
syntax on
set expandtab
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set autoindent
set smartindent

set history=128
set autoread
set cmdheight=1
set hlsearch
set magic
set incsearch
set laststatus=2
set fileencodings=utf-8,gbk,gb2312

set t_Co=256
set timeoutlen=700
set pastetoggle=<F12>
set ignorecase
set smartcase
filetype indent plugin on
set hidden
set bkc=yes
set wrap
set linebreak
" end

set rtp+=~/.vim/plugged/vim-jsx/after/syntax/jsx.vim

" color
let g:solarized_termcolors=256
syntax enable
set background=light
colorscheme solarized
"colorscheme dracula
"colorscheme jellybeans
" end

" set bundle

" ycm
let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]
let g:ycm_global_ycm_extra_conf = "~/.vim/ycm_extra_conf.py"
let g:ycm_min_num_of_chars_for_completion = 2
let g:ycm_complete_in_comments = 1

" ultisnips
let g:UltiSnipsExpandTrigger="<c-e>"
let g:UltiSnipsListSnippets="<c-s-l>"
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsJumpForwardTrigger="<c-l>"
let g:UltiSnipsJumpBackwardTrigger="<c-j>"

" vim-javascript
let g:javascript_plugin_flow = 1
let g:javascript_plugin_jsdoc = 1

" emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css,markdown,javascript EmmetInstall

" vim-airline
"let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='tomorrow'

" markdown preview
let g:livedown_browser = "google-chrome-stable"

" vim-jsx
let g:jsx_ext_required = 0


" editor config
let g:EditorConfig_exclude_patterns = ['scp://.*']
"let g:EditorConfig_core_mode = 'external_command'

" auto pair
let g:AutoPairsShortcutFastWrap = '<C-e>w'
let g:AutoPairsShortcutToggle = '<C-e>a'
