apiVersion: v1
kind: Pod
metadata:
  name: pod-dev
  labels:
    pod: dev
spec:
  containers:
    - name: pgAdmin
      image: docker.io/dpage/pgadmin4
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: linxray@gmail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pgAdmin@1290
      ports:
        - containerPort: 80
          hostIP: 127.0.0.1
          hostPort: 9000
      volumeMounts:
        - name: pg-admin-data
          mountPath: /var/lib/pgadmin
        - name: pg-admin-log
          mountPath: /var/log/pgadmin

    - name: postgres
      image: docker.io/library/postgres:15-alpine
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: linxray@gmail.com
        - name: POSTGRES_PASSWORD
          value: postgres@1290
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
        - name: pg-init-db
          mountPath: /docker-entrypoint-initdb.d/init-db.sh

  initContainers:
    - name: change-pgadmin-volume-perms
      image: docker.io/library/busybox
      command: ["/bin/chown", "-R", "5050:5050", "/var/lib/pgadmin", "/var/log/pgadmin"]
      volumeMounts:
        - name: pg-admin-data
          mountPath: /var/lib/pgadmin
        - name: pg-admin-log
          mountPath: /var/log/pgadmin

  volumes:
    - name: pg-data
      persistentVolumeClaim:
        claimName: pg-data
    - name: pg-init-db
      hostPath:
        path: postgres-init-db.sh
        type: File

    - name: pg-admin-data
      persistentVolumeClaim:
        claimName: pg-admin-data

    - name: pg-admin-log
      persistentVolumeClaim:
        claimName: pg-admin-log
