# SPDX-License-Identifier: LGPL-2.1-only
#
#  Copyright IBM Corporation. 2007
#
#  Authors:	Balbir Singh <balbir@linux.vnet.ibm.com>
#
#group daemons/www {
#	perm {
#		task {
#			uid = root;
#			gid = webmaster;
#		}
#		admin {
#			uid = root;
#			gid = root;
#		}
#	}
#	cpu {
#		cpu.shares = 1000;
#	}
#}
#
#group daemons/ftp {
#	perm {
#		task {
#			uid = root;
#			gid = ftpmaster;
#		}
#		admin {
#			uid = root;
#			gid = root;
#		}
#	}
#	cpu {
#		cpu.shares = 500;
#	}
#}
#
#mount {
#	cpu = /sys/fs/cgroup/cpu;
#	cpuacct = /sys/fs/cgroup/cpuacct;
#}

group browser/ram {
	perm {
		task {
			uid = 1000;
			gid = 1000;
		}
		admin {
			uid = 1000;
			gid = 1000;
		}
	}

	memory {
		memory.max = 2G;
	}
}
